name: SemanticVersioner
description: >
  A GitHub Action to increment the version based on convention commits and whether we are in a dev or main branch
author: Hugh Macdonald

inputs:
  main-branch:
    description: The main branch to use
    required: false
    default: main
  dev-branch:
    description: The development branch to use (if required)
    required: false
    default: ""
  dev-suffix:
    description: The suffix to use for development versions
    required: false
    default: dev
  include-shorter-versions:
    description: Include shorter versions of tags that move as new versions are created
    required: false
    default: "false"
  skip-python-install:
    description: Skip the installation of Python (if it's already installed)
    required: false
    default: "false"
  use-semantic-dev-versions:
    description: >
      Whether to use semantic versioning for the development (suffix) versions. If this
      is set to false, the development versions will be a simple incrementing number. If
      this is set to true, the development versions will be something like 1.2.3-dev.4.5.6
    required: false
    default: "false"


outputs:
  previous-version:
    description: >
      The version before the version was incremented. This may be the same as the new version.
    value: ${{ steps.increment-version.outputs.previous-version }}
  new-version:
    description: >
      The new version after the version was incremented. This may be the same as the previous
      version.
    value: ${{ steps.increment-version.outputs.new-version }}

runs:
  using: "composite"
  steps:
    - name: Set up Python
      if: ${{ !contains(fromJSON('["1", "y", "yes", "on", "true", "t"]'), inputs.skip-python-install) }}
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      uses: BSFishy/pip-action@v1
      with:
        packages: |
          semver
          gitpython

    - name: Increment version
      id: increment-version
      run: python ${{ github.action_path }}/main.py
      shell: ${{ runner.os == 'Windows' && 'powershell' || 'bash' }}
      env:
        GIT_EMAIL: ${{ inputs.git-email }}
        GIT_USERNAME: ${{ inputs.git-username }}
        MAIN_BRANCH: ${{ inputs.main-branch }}
        DEV_BRANCH: ${{ inputs.dev-branch }}
        DEV_SUFFIX: ${{ inputs.dev-suffix }}
        INCLUDE_SHORTER_VERSIONS: ${{ inputs.include-shorter-versions }}
        USE_SEMANTIC_DEV_VERSIONS: ${{ inputs.use-semantic-dev-versions }}
        PUSH: 1

branding:
  color: blue
  icon: arrow-up-circle
