name: FilamentVersioner
description: >
  A GitHub Action to increment the version based on convention commits and whether we are in a dev or main branch
author: Hugh Macdonald

inputs:
  main-branch:
    description: The main branch to use
    required: false
    default: main
  dev-branch:
    description: The development branch to use (if required)
    required: false
    default: ""
  dev-suffix:
    description: The suffix to use for development versions
    required: false
    default: dev

outputs:
  previous-version:
    description: >
      The version before the version was incremented. This may be the same as the new version.
    value: ${{ steps.increment-version.outputs.previous-version }}
  new-version:
    description: >
      The new version after the version was incremented. This may be the same as the previous
      version.
    value: ${{ steps.increment-version.outputs.new-version }}

runs:
  using: "composite"
  steps:
    - name: Print action path
      run: echo "${GITHUB_ACTION_PATH}"
      shell: bash

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      uses: BSFishy/pip-action@v1
      with:
        packages: |
          semver==3.0.4
          gitpython==3.1.44

    - name: Increment version
      id: increment-version
      working-directory: ${GITHUB_ACTION_PATH}
      run: python main.py
      shell: bash
      env:
        GIT_EMAIL: ${{ inputs.git-email }}
        GIT_USERNAME: ${{ inputs.git-username }}
        MAIN_BRANCH: ${{ inputs.main-branch }}
        DEV_BRANCH: ${{ inputs.dev-branch }}
        DEV_SUFFIX: ${{ inputs.dev-suffix }}
        PUSH: 1

    - name: Print outputs
      run: echo "Updated version. $PREVIOUS_VERSION -> $NEW_VERSION"
      shell: bash
      env:
        PREVIOUS_VERSION: ${{ steps.increment-version.outputs.previous-version }}
        NEW_VERSION: ${{ steps.increment-version.outputs.new-version }}

branding:
  color: blue
  icon: arrow-up-circle